# Generated by Django 4.1 on 2024-02-29 11:04

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("user", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("view_cnt", models.IntegerField(default=0)),
                (
                    "reg_date",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
        ),
    ]
